project:
  stage: custom
swarm:
  ee:
    spec-descriptor-property-replacement: true
  datasources:
    data-sources:
      ClarksnutDS:
        jndi-name: java:jboss/datasources/ClarksnutDS
        driver-name: h2
        connection-url: jdbc:h2:mem:test;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
        user-name: sa
        password: sa
clarksnut:
  fileStorage:
    provider: jpa
  report:
    default: clarksnut
    cacheReports: true
    cacheTemplates: true
    folder:
      dir: "/reports"
  theme:
    default: clarksnut
    staticMaxAge: 2592000
    cacheThemes: true
    cacheTemplates: true
    folder:
      dir: "/themes"
  mail:
    vendor:
      gmail:
        applicationName: "Clarksnut"