metadata:
  name: openfact-sync-db
  labels:
    service: openfact-sync-db
spec:
  replicas: 1
  selector:
    service: openfact-sync-db
  template:
    metadata:
      labels:
        service: openfact-sync-db
    spec:
      containers:
      - name: openfact-sync-db
        image: registry.centos.org/postgresql/postgresql:9.6
        imagePullPolicy: IfNotPresent
        env:
        - name: POSTGRESQL_DATABASE
          value: openfactsync
        - name: POSTGRESQL_PASSWORD
          value: openfactsync
        - name: POSTGRESQL_USER
          value: openfactsync
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        livenessProbe:
          exec:
            command:
            - sh
            - -c
            - exec pg_isready --host $POD_IP
          initialDelaySeconds: 60
          timeoutSeconds: 5
          failureThreshold: 6
        readinessProbe:
          exec:
            command:
            - sh
            - -c
            - exec pg_isready --host $POD_IP
          initialDelaySeconds: 20
          timeoutSeconds: 3
          periodSeconds: 5
        ports:
        - containerPort: 5432
          protocol: TCP
        volumeMounts:
        - mountPath: /var/lib/pgsql
          name: openfact-sync-db-postgresql-data
          readOnly: false
      volumes:
      - name: openfact-sync-db-postgresql-data
        persistentVolumeClaim:
          claimName: openfact-sync-db-postgresql-data