metadata:
  name: ${project.artifactId}
spec:
  replicas: 1
  strategy:
    rollingParams:
      timeoutSeconds: 10800
    type: Rolling
  template:
    metadata:
      annotations:
        pod.beta.kubernetes.io/init-containers: |-
            [
            ]
    spec:
      containers:
      - env:
        - name: KUBERNETES_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: JAVA_APP_DIR
          value: /deployments
        - name: SSO_AUTH_SERVER_URL
          value: ${SSO_AUTH_SERVER_URL}
        - name: JAVA_OPTIONS
          value: -Dsso.realm=${SSO_REALM} -Dsso.auth.server.url=${SSO_AUTH_SERVER_URL} -Dsso.clientId=${SSO_CLIENT_ID} -Dsso.credentials.secret=${SSO_CREDENTIALS_SECRET}
        - name: DB_DRIVER_NAME
          valueFrom:
            configMapKeyRef:
              name: ${project.artifactId}
              key: db.driver
        - name: DB_CONNECTION_URL
          valueFrom:
            configMapKeyRef:
              name: ${project.artifactId}
              key: db.url
        - name: DB_USER_NAME
          valueFrom:
            secretKeyRef:
              name: ${project.artifactId}
              key: db.user
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: ${project.artifactId}
              key: db.password
        - name: HIBERNATE_STRATEGY
          valueFrom:
            configMapKeyRef:
              name: ${project.artifactId}
              key: hibernate.strategy
        - name: HIBERNATE_SHOW_SQL
          valueFrom:
            configMapKeyRef:
              name: ${project.artifactId}
              key: hibernate.show_sql
        - name: HIBERNATE_FORMAT_SQL
          valueFrom:
            configMapKeyRef:
              name: ${project.artifactId}
              key: hibernate.format_sql
        - name: HIBERNATE_SECOND_LEVEL_CACHE
          valueFrom:
            configMapKeyRef:
              name: ${project.artifactId}
              key: hibernate.second_level_cache
        - name: ES_HOST
          valueFrom:
            configMapKeyRef:
              name: ${project.artifactId}
              key: es.url
        - name: ES_USER
          valueFrom:
            secretKeyRef:
              name: ${project.artifactId}
              key: es.user
        - name: ES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: ${project.artifactId}
              key: es.password
        - name: ES_INDEX_SCHEMA_MANAGEMENT_STRATEGY
          valueFrom:
            configMapKeyRef:
              name: ${project.artifactId}
              key: es.index_strategy
        - name: ES_REQUIRED_INDEX_STATUS
          valueFrom:
            configMapKeyRef:
              name: ${project.artifactId}
              key: es.required_index_status
        - name: GMAIL_CLIENT_APPLICATION_NAME
          valueFrom:
            secretKeyRef:
              name: ${project.artifactId}
              key: gmail.applicationName
        - name: OPENFACT_FILE_STORAGE_PROVIDER
          valueFrom:
            configMapKeyRef:
              name: ${project.artifactId}
              key: openfact.fileStorage.provider
        - name: OPENFACT_REPORT_DEFAULT
          valueFrom:
            configMapKeyRef:
              name: ${project.artifactId}
              key: openfact.report.default
        - name: OPENFACT_REPORT_CACHE_REPORTS
          valueFrom:
            configMapKeyRef:
              name: ${project.artifactId}
              key: openfact.report.cacheReports
        - name: OPENFACT_REPORT_CACHE_TEMPLATES
          valueFrom:
            configMapKeyRef:
              name: ${project.artifactId}
              key: openfact.report.cacheTemplates
        - name: OPENFACT_REPORT_FOLDER_DIR
          valueFrom:
            configMapKeyRef:
              name: ${project.artifactId}
              key: openfact.report.folder.dir
        - name: OPENFACT_THEME_DEFAULT
          valueFrom:
            configMapKeyRef:
              name: ${project.artifactId}
              key: openfact.theme.default
        - name: OPENFACT_THEME_STATIC_MAX_AGE
          valueFrom:
            configMapKeyRef:
              name: ${project.artifactId}
              key: openfact.theme.staticMaxAge
        - name: OPENFACT_THEME_CACHE_THEMES
          valueFrom:
            configMapKeyRef:
              name: ${project.artifactId}
              key: openfact.theme.cacheThemes
        - name: OPENFACT_THEME_CACHE_TEMPLATES
          valueFrom:
            configMapKeyRef:
              name: ${project.artifactId}
              key: openfact.theme.cacheTemplates
        - name: OPENFACT_THEME_FOLDER_DIR
          valueFrom:
            configMapKeyRef:
              name: ${project.artifactId}
              key: openfact.theme.folder.dir
        name: ${project.artifactId}
        image: ${project.artifactId}:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 10
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 60
          periodSeconds: 30
        securityContext:
          privileged: false
  triggers:
  - type: ConfigChange
  - imageChangeParams:
      automatic: true
      containerNames:
      - ${project.artifactId}
      from:
        kind: ImageStreamTag
        name: ${project.artifactId}:latest
    type: ImageChange
