metadata:
  name: ${project.artifactId}
spec:
  replicas: 1
  strategy:
    rollingParams:
      timeoutSeconds: 10800
    type: Rolling
  template:
    metadata:
      annotations:
        pod.beta.kubernetes.io/init-containers: |-
            [
            ]
    spec:
      containers:
      - env:
        - name: KUBERNETES_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: JAVA_APP_DIR
          value: /deployments
        - name: SSO_AUTH_SERVER_URL
          value: ${SSO_AUTH_SERVER_URL}
        - name: JAVA_OPTIONS
          value: -Dsso.realm=${SSO_REALM} -Dsso.auth.server.url=${SSO_AUTH_SERVER_URL} -Dsso.clientId=${SSO_CLIENT_ID} -Dsso.credentials.secret=${SSO_CREDENTIALS_SECRET} -Ddatabase=${DS_DRIVER} -Ddatabase.url=${DS_URL} -Ddatabase.username=${DS_USERNAME} -Ddatabase.password=${DS_PASSWORD} -Dhibernate.hbm2ddl.auto=${HB_AUTO} -Dhibernate.show_sql=${HB_SHOW_SQL} -Dhibernate.format_sql=${HB_FORMAT_SQL} -Dhibernate.cache.use_second_level_cache=${HB_SECOND_LEVEL_CACHE} -Dhibernate.es.host=${ES_SERVER_URL} -Dhibernate.es.username=${ES_USERNAME} -Dhibernate.es.password=${ES_PASSWORD} -Dhibernate.es.index_schema_management_strategy=${ES_INDEX_SCHEMA_MANAGEMENT_STRATEGY} -Dhibernate.es.required_index_status=${ES_REQUIRED_INDEX_STATUS}
        - name: GMAIL_CLIENT_APPLICATION_NAME
          valueFrom:
            secretKeyRef:
              name: openfact-sync
              key: gmail.client.applicationName
        - name: OPENFACT_FILE_STORAGE_PROVIDER
          valueFrom:
            configMapKeyRef:
              name: ${project.artifactId}
              key: openfact.fileStorage.provider
        - name: OPENFACT_REPORT_DEFAULT
          valueFrom:
            configMapKeyRef:
              name: ${project.artifactId}
              key: openfact.report.default
        - name: OPENFACT_REPORT_CACHE_REPORTS
          valueFrom:
            configMapKeyRef:
              name: ${project.artifactId}
              key: openfact.report.cacheReports
        - name: OPENFACT_REPORT_CACHE_TEMPLATES
          valueFrom:
            configMapKeyRef:
              name: ${project.artifactId}
              key: openfact.report.cacheTemplates
        - name: OPENFACT_REPORT_FOLDER_DIR
          valueFrom:
            configMapKeyRef:
              name: ${project.artifactId}
              key: openfact.report.folder.dir
        - name: OPENFACT_THEME_DEFAULT
          valueFrom:
            configMapKeyRef:
              name: ${project.artifactId}
              key: openfact.theme.default
        - name: OPENFACT_THEME_STATIC_MAX_AGE
          valueFrom:
            configMapKeyRef:
              name: ${project.artifactId}
              key: openfact.theme.staticMaxAge
        - name: OPENFACT_THEME_CACHE_THEMES
          valueFrom:
            configMapKeyRef:
              name: ${project.artifactId}
              key: openfact.theme.cacheThemes
        - name: OPENFACT_THEME_CACHE_TEMPLATES
          valueFrom:
            configMapKeyRef:
              name: ${project.artifactId}
              key: openfact.theme.cacheTemplates
        - name: OPENFACT_THEME_FOLDER_DIR
          valueFrom:
            configMapKeyRef:
              name: ${project.artifactId}
              key: openfact.theme.folder.dir
        name: ${project.artifactId}
        image: ${project.artifactId}:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 10
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 60
          periodSeconds: 30
        securityContext:
          privileged: false
  triggers:
  - type: ConfigChange
  - imageChangeParams:
      automatic: true
      containerNames:
      - ${project.artifactId}
      from:
        kind: ImageStreamTag
        name: ${project.artifactId}:latest
    type: ImageChange
