metadata:
  name: elasticsearch
  labels:
    service: elasticsearch
spec:
  replicas: 1
  selector:
    service: elasticsearch
  template:
    metadata:
      labels:
        service: elasticsearch
    spec:
      containers:
      - image: docker.elastic.co/elasticsearch/elasticsearch:${elasticsearch.version}
        env:
        imagePullPolicy: IfNotPresent
        name: elasticsearch
        ports:
        - containerPort: 9200
          protocol: TCP
        volumeMounts:
        - mountPath: /usr/share/elasticsearch/data
          name: elasticsearch-data
          readOnly: false
      volumes:
      - name: elasticsearch-data
        persistentVolumeClaim:
          claimName: elasticsearch-data